### ISSUE TITLE
Add text or red boxes to highlight that "Both" and http(s) for backend is needed for API import Cal API. 

### ISSUE THREAD

**Issue by Chad-Dumas-MSFT** [Azure/apim-lab#78]
When adding the Calculator API and on use if in settings "both" and Url is not set to http(s) it will come back to an HTTP 500 error.  While this will likely be passed over by those knowledgeable to the service it may cause a blocker to those not familiar with the setting as it is an HTTP call.  Also, if you it can be specified why this is needed to not arrive at the HTTP 500 would be great.

**Comment by simonkurtz-MSFT** [comment]
We can call that out more explicitly if it can help our users. I will see to this.

As for why, there is a bit of history to it. The backend only runs on `http`, but we can't expose `http` as the only means to get to it due to subsequent CORS policy violations that would occur. Frankly, in this day and age, the backend just needs to be https. @ferantoMSFT and I were tossing about some ideas on how we can improve that. I can address the immediate ask here, then will take this internal to work through.

For reference, we are talking about [Import API from Swagger](https://azure.github.io/apim-lab/apim-lab/3-addingApis/apimanagement-3-2.html).
